Modena_Eventi/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path("listaeventi/", ListaEventiView.as_view(), name="listaeventi"), #Accessibile da: Utenti, Anonymous
    path("prenotazioni/utente/", PrenotazioniUtenteView.as_view(), name="prenotazioni_utente"), #Accessibile da: Utenti
    path("prenotazioni/pubblicatore/", PrenotazioniPubblicatoreView.as_view(), name="prenotazioni_pubblicatore"), #Accessibile da: Pubblicatori
    path("evento/<int:pk>/", DetailEventoView.as_view(), name="visualizza_evento"), #Accessibile da: Utenti
    path("pubblicatore/<int:pk>/", DetailPubblicatoreView.as_view(), name="visualizza_pubblicatore"), #Accessibile da: Utenti
    path("cercaevento/", CercaEvento.as_view(), name="cerca_evento"), #Accessibile da: Utenti, Anonymous
    path("prenotazioneconfermata/", PrenotazioneConfermataView.as_view(), name="prenotazione_confermata"), #Accessibile da: Utenti
    path("gestiscieventi/", ListaEventiPerPubblicatoreView.as_view(), name="gestisci_eventi"), #Accessibile da: Pubblicatore
    path("recensioni/<int:evento_id>/", RecensioniEventoView.as_view(), name="recensioni_evento"), #Accessibile da: Utenti

    path('recensione/<int:prenotazione_id>/', salva_recensione, name="salva_recensione"), #Accessibile da: Utenti
    path('creaevento/', create_evento, name="crea_evento"), #Accessibile da: Pubblicatore
    path('eliminaevento/<int:pk>/', elimina_evento, name="elimina_evento"), #Accessibile da: Pubblicatore
    path('home/', home_page, name="homepage"),
    path("eliminaprenotazione/<int:pk>/", elimina_prenotazione, name="elimina_prenotazione") #Accessibile da: Utenti, Pubblicatore
]

Modena_Eventi/modena_eventi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler403, handler404
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls, name="adminpage"),
    path('core/', include('core.urls')),
    path('users/', include('utenti.urls')),
    re_path(r'^$|^/$|^home/$', home_page, name='homepage'),
    re_path(r'^.*', resource_not_found_view, name='notfound'),
]

Modena_Eventi/utenti/urls.py
from django.urls import path
from .views import *

app_name = 'utenti'

urlpatterns = [
    path('register/', register, name='register'),
    path('utenteregister/', UtenteRegistrationView.as_view(), name='utente_registration'),
    path('pubblicatoreregister/',PubblicatoreRegistrationView.as_view(), name='pubblicatore_registration'),
    path('login/',login_request, name='login'),
    path('logout/',logout_request, name='logout'),
    path('profile/', view_profile, name='view_profile'),
    path('updateprofile/', update_profile, name='update_profile'),
    path('cambiapassword/', cambia_password, name='cambia_password')
]

Modena_Eventi/utenti/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
#from django.contrib.auth.models import User

# Create your models here.


class User(AbstractUser):
    
    # campi che aiutano a capire se un utente è una struttura o un utente
    is_pubblicatore = models.BooleanField(default=False)
    is_utente = models.BooleanField(default=False)
    img = models.ImageField(upload_to='static/img/users_img/profile_pic', default='static/img/default_img/no_img_profile.jpg')
    
    class Meta:
        verbose_name_plural = "Users"



class Pubblicatore(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    descrizione = models.CharField(max_length=500)
    latitudine = models.FloatField()
    longitudine = models.FloatField()
    numTelefono = models.CharField(max_length=20, default="+393806437638")

    def __str__(self):
        return self.user.first_name + ": " + self.descrizione + " (" + str(self.latitudine) + ", " + str(self.longitudine) + ")"


    class Meta:
        verbose_name_plural = "Pubblicatori"




class Utente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


    class Meta:
        verbose_name_plural = "Utenti"

Modena_Eventi/utenti/views.py
from django.views.generic import CreateView
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib import messages
from django.contrib.auth import login, logout,authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from .models import *
from utenti.form import *
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):
    if request.user.is_authenticated:
        raise PermissionDenied
    return render(request, 'utenti/register.html')

def PubblicatoreUpdateView(request):       
    if not request.user.is_authenticated:
        raise PermissionDenied
    
    if not request.user.is_pubblicatore:
        raise PermissionDenied
    
    pubblicatore = get_object_or_404(Pubblicatore, user = request.user)

    initial_data = {
        "init_nome": request.user.first_name,
        "init_descrizione": pubblicatore.descrizione,
        "init_latitudine": pubblicatore.latitudine,
        "init_longitudine": pubblicatore.longitudine,
        "init_numTelefono": pubblicatore.numTelefono
    }
    print(initial_data)
    
    if request.method == "POST":
        pubblicatore_form = UpdatePubblicatoreForm(request.POST, instance=pubblicatore)
        user_form = UpdateUserForm(request.POST, request.FILES, instance=request.user)

        if user_form.is_valid() and pubblicatore_form.is_valid():
            pubblicatore_form.save()
            user_form.save()
            return redirect("/users/profile/?modified=ok")
        else:
            error_fields = [
                field
                for form in [pubblicatore_form, user_form]
                for field, error_list in form.errors.as_data().items()
                if error_list
            ]
            error_params = '&'.join(f'{field}=no' for field in error_fields)
            return redirect(f'/users/profile/?modified=no&{error_params}')
    else:
        #Utente non ha campi da modificare se non il nome di user
        initial_data["init_cognome"] = request.user.last_name
        initial_data["img"] = request.user.img
        user_form = UpdateUserForm(instance=request.user)

    return render(request, "utenti/edit_profile_pubblicatore.html",
                  {
                      "user_form": user_form,
                      "initial_data": initial_data
                  }
                  )

def UtenteUpdateView(request):
    if not request.user.is_authenticated:
        raise PermissionDenied
    
    if not request.user.is_utente:
        raise PermissionDenied
    
    utente = get_object_or_404(Utente, user=request.user)
    initial_data = {
        'init_nome': request.user.first_name,
        'init_cognome': request.user.last_name
    }

    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
        if user_form.is_valid():
            print(user_form)
            user_form.save()
            return redirect('/users/profile/?modified=ok')
        else:
            error_fields = [
                field
                for field, error_list in user_form.errors.as_data().items()
                if error_list
            ]
            error_params = '&'.join(f'{field}=no' for field in error_fields)
            return redirect(f'/users/profile/?modified=no&{error_params}')
    else:
        user_form = UpdateUserForm(instance=request.user)

    return render(request, "utenti/edit_profile_utente.html",
                  {
                      "user_form": user_form,
                      "initial_data": initial_data
                  }
                  )

class UtenteRegistrationView(CreateView):
    model = User
    form_class = UtenteSignUpForm
    template_name = 'utenti/utente_register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/core/cercaevento/?registration=ok')
    
class PubblicatoreRegistrationView(CreateView):
    model = User
    form_class = PubblicatoreSignUpForm
    template_name = "utenti/pubblicatore_register.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/core/gestiscieventi/?registration=ok')
    
#----LOGIN----
    
def login_request(request):
    if request.user.is_authenticated:
        raise PermissionDenied
    next_url = request.GET.get('next') or request.POST.get('next') or '/?login=ok'

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if next_url:
                    return redirect(next_url)

            else:
                messages.error(request, "Username o password sbagliati.")
        else:
            messages.error(request, "Username o password sbagliati.")
    
    return render(request, 'utenti/login.html', context={'form': AuthenticationForm(), 'next': next_url}) 

@login_required
def logout_request(request):
    logout(request)
    return redirect('/?logout=ok')

@login_required
def view_profile(request):
    user = get_object_or_404(User, pk=request.user.pk)
    
    if user.is_utente:
        profile_data = {
            'user': user,
            'utente': get_object_or_404(Utente, user=user)
        }
    elif user.is_pubblicatore:
        admin_email = User.objects.filter(is_staff=True).values_list('email', flat=True).first()

        profile_data = {
            'user': user,
            'pubblicatore': get_object_or_404(Pubblicatore, user=user),
            'admin_email' : admin_email
        }

    return render(request, 'utenti/profile_detail.html', profile_data)

@login_required
def update_profile(request):
    user = request.user
    if user.is_utente:
        utente_view = UtenteUpdateView
        return utente_view(request)
    elif user.is_pubblicatore:
        pubblicatore_view = PubblicatoreUpdateView
        return pubblicatore_view(request)
    else:
        raise Exception("Errore")

@login_required
def cambia_password(request):
    
    if request.method == 'POST':
        form = CambiaPasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  
            return redirect(reverse('utenti:view_profile') + '?changed=ok')
    else:
        form = CambiaPasswordForm(request.user)

    return render(request, 'utenti/cambia_password.html', {'form': form})

Modena_Eventi/utenti/templates/utenti/edit_profile_pubblicatore.html
{% extends "base.html" %}

{% block title %}Modifica dati profilo{% endblock %}

{% block content %}
<style>
    .image-container {
        width: 170px;
        height: 170px;
        border: solid;
        border-radius: 50%;
        overflow: hidden;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0 auto;  /* Aggiungi questa riga per centrare il contenitore dell'immagine */
    }
    
    .image-container img {
        width: 150%;
        height: 150%;
        object-fit: cover;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <section>
                <div class="card border-0">
                    <div class="card-header text-center bg-transparent">
                        <h2 class="h4 mb-0 text-dark">Profilo di {{ request.user.username }}</h2>
                    </div>
                    <div class="card-body p-4">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <!-- Nome Pubblicatore -->
                            <div class="mb-3">
                                <label for="id_first_name" class="form-label"><strong>Nome Pubblicatore</strong></label>
                                <input type="text" id="id_first_name" name="first_name" value="{{ initial_data.init_nome }}" class="form-control" required>
                            </div>

                            <!-- Latitudine -->
                            <div class="mb-3">
                                <label for="id_latitudine" class="form-label"><strong>Latitudine</strong></label>
                                <input type="number" id="id_latitudine" name="latitudine" value="{{ initial_data.init_latitudine }}" class="form-control" required>
                            </div>

                            <!-- Longitudine -->
                            <div class="mb-3">
                                <label for="id_longitudine" class="form-label"><strong>Longitudine</strong></label>
                                <input type="number" id="id_longitudine" name="longitudine" value="{{ initial_data.init_longitudine }}" class="form-control" required>
                            </div>

                            <!-- Telefono -->
                            <div class="mb-3">
                                <label for="id_numTelefono" class="form-label"><strong>Telefono:</strong></label>
                                <input type="text" id="id_numTelefono" name="numTelefono" value="{{ initial_data.init_numTelefono }}" class="form-control" required>
                            </div>

                            <!-- Descrizione -->
                            <div class="mb-3">
                                <label for="id_descrizione" class="form-label"><strong>Descrizione</strong></label>
                                <textarea id="id_descrizione" name="descrizione" class="form-control" rows="3" required>{{ initial_data.init_descrizione }}</textarea>
                            </div>

                            <!-- Immagine -->
                            <div class="row pt-3 justify-content-center">  
                                <label for="id_img" class="col-md-4 col-form-label text-md-right"><strong>Immagine </strong></label>     
                                <div class="col">
                                    <input type="file" id="id_img" name="img" class="form-control">
                                </div>
                            </div>

                            <!-- Bottoni -->
                            <div class="d-flex justify-content-between pt-3">
                                <a href="{% url 'utenti:view_profile' %}" class="btn btn-outline-secondary" style="border-radius: 20px;">Annulla</a>
                                <button type="submit" class="btn btn-primary btn-rounded" style="border-radius: 20px;">Salva</button>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
{% endblock content %}

Modena_Eventi/utenti/templates/utenti/edit_profile_utente.html
{% extends "base.html" %}

{% block title %}Modifica dati profilo{% endblock title %}
{% load static %}

<style>
  .image-container {
      width: 170px;
      height: 170px;
      border: solid;
      border-radius: 50%;
      overflow: hidden;
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 0 auto;  /* Aggiungi questa riga per centrare il contenitore dell'immagine */
  }
  
  .image-container img {
      width: 150%;
      height: 150%;
      object-fit: cover;
  }
</style>

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow-sm border-0">
          <div class="card-header text-center bg-light border-bottom">
            <h2 class="mb-0">Modifica Profilo</h2>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                <label for="id_first_name" class="form-label"><strong>Nome</strong></label>
                <input type="text" id="id_first_name" name="first_name" value="{{ user.first_name }}" class="form-control">
              </div>
              <div class="form-group mt-3">
                <label for="id_last_name" class="form-label"><strong>Cognome</strong></label>
                <input type="text" id="id_last_name" name="last_name" value="{{ user.last_name }}" class="form-control">
              </div>
              <div class="row pt-3 justify-content-center">  
                <label for="id_img" class="col-md-4 col-form-label text-md-right"><strong>Immagine </strong></label>     
                <div class="col">
                    <input type="file" id="id_img" name="img" class="form-control">
                </div>
              </div>
              <div class="text-center mt-4">
                <a href="{% url 'utenti:view_profile' %}" class="btn btn-outline-secondary mr-2" style="border-radius: 25px;">Annulla</a>
                <button type="submit" class="btn btn-primary" style="border-radius: 25px;">Salva</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Modena_Eventi/utenti/templates/utenti/login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
<style>
  .card-header {
    background-color: #e0e0d1; /* Beige */
    color: #333; /* Colore scuro per il testo */
    font-weight: bold;
}

.card {
    border-radius: 12px; /* Arrotonda gli angoli della card */
}
</style>
<section>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header text-black text-center">
            <h2>Login</h2>
          </div>
          <div class="card-body">
            <form action="{% url 'utenti:login' %}" method="POST" novalidate>
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}">
              
              {% for field in form.visible_fields %}
                <div class="form-group">
                  <label for="{{ field.id_for_label }}"><strong>{{ field.label }}</strong></label>
                  {% render_field field class="form-control" %}
                  {% if field.errors %}
                    {% for error in field.errors %}
                      <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                  {% endif %}
                </div>
              {% endfor %}
              
              {% if messages %}
                <div class="alert alert-danger" role="alert">
                  {% for message in messages %}
                    {{ message }}
                  {% endfor %}
                </div>
              {% endif %}

              <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary btn-block font-weight-bold">Login</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Modena_Eventi/utenti/templates/utenti/profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Profilo di {{ user.username }} {% endblock %}

{% block content %}
<style>
    .image-container {
        width: 170px;
        height: 170px;
        border: solid;
        border-radius: 50%;
        overflow: hidden;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0 auto;  /* Aggiungi questa riga per centrare il contenitore dell'immagine */
    }
    
    .image-container img {
        width: 150%;
        height: 150%;
        object-fit: cover;
    }

    /* Alerts */
    .alert {
        border-radius: 0.5rem;
    }
    .card-header {
        background-color: #e0e0d1; /* Beige */
        color: #333; /* Colore scuro per il testo */
        font-weight: bold;
    }
    
    .card {
        border-radius: 12px; /* Arrotonda gli angoli della card */
    }
</style>

<!-- Aggiungi i link ai file CSS e JavaScript di Selectize.js -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap5.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"></script>
    

    <!-- Alert per la corretta modifica dati -->
    {% if "ok" in request.GET.modified %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Modifiche avvenute con successo!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <!-- Alert per la corretta modifica pw -->
    {% if "ok" in request.GET.changed %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Password cambiata con successo!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <!-- Alert per errore di modifica dati -->
    {% if "no" in request.GET.modified %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Errore durante l'operazione!</strong>
        <p>I seguenti eventi non erano in un formato valido:</p>
        <ul>
            {% for key, value in request.GET.items %}
                {% if key != "modified" %}
                    <li>{{ key }}</li>
                {% endif %}
            {% endfor %}
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}



    <!-- Profilo Utente -->
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center">
                        <h2>Profilo di {{ user.username }}</h2>
                    </div>
                    <div class="card-body">
                        {% if user.is_utente %}
                        <dl class="row">
                            <dt class="col-sm-3">Nome:</dt>
                            <dd class="col-sm-9">{{ user.first_name }}</dd>
                            <dt class="col-sm-3">Cognome:</dt>
                            <dd class="col-sm-9">{{ user.last_name }}</dd>
                            <dd class="image-container"><img src="{{ user.img.url }}" alt="Profile Image"></dd>
                        </dl>
                        {% elif user.is_pubblicatore %}
                        <h4 class="text-center">Dati del Pubblicatore</h4>
                        <dl class="row">
                            <dt class="col-sm-3">Latitudine:</dt>
                            <dd class="col-sm-9">{{ pubblicatore.latitudine }}</dd>
                            <dt class="col-sm-3">Longitudine:</dt>
                            <dd class="col-sm-9">{{ pubblicatore.longitudine }}</dd>
                            <dt class="col-sm-3">Descrizione:</dt>
                            <dd class="col-sm-9">{{ pubblicatore.descrizione }}</dd>
                            <dt class="col-sm-3">Telefono:</dt>
                            <dd class="col-sm-9">{{ pubblicatore.numTelefono }}</dd>
                            <dd class="image-container"><img src="{{ user.img.url }}" alt="Profile Image"></dd>
                        </dl>
                        {% endif %}
                        <div class="text-center mt-4">
                            <a href="{% url 'utenti:update_profile' %}" class="btn btn-secondary">Modifica Profilo</a>
                            <a href="{% url 'utenti:cambia_password' %}" class="btn btn-secondary">Cambia Password</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Modena_Eventi/utenti/templates/utenti/pubblicatore_register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Registrazione Pubblicatore{% endblock %}

{% block content %}
<style>
    .card-header {
        background-color: #e0e0d1; /* Beige */
        color: #333; /* Colore scuro per il testo */
        font-weight: bold;
    }
    .card {
        border-radius: 12px; /* Arrotonda gli angoli della card */
    }
    .form-control {
        border-radius: 5px;
    }
    .text-danger {
        font-size: 0.9rem;
    }
    .container {
        max-width: 500px;
    }
    h2 {
        font-size: 1.75rem;
        margin-bottom: 0;
    }
    h4 {
        font-size: 1.25rem;
        margin-top: 1rem;
        color: #007bff;
    }
    .btn-block {
        border-radius: 25px;
        padding: 10px 20px;
        font-size: 1.1rem;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Registrazione Pubblicatore</h2>
                </div>
                <div class="card-body px-4">
                    <form action="{% url 'utenti:pubblicatore_registration' %}" method="POST" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">
                                    {% if field.label == "Password confirmation" %}
                                        Conferma Password
                                    {% else %}
                                        {{ field.label }}
                                    {% endif %}
                                </label>
                                {% render_field field class="form-control" %}
                                {% if field.errors %}
                                    <div class="text-danger">
                                        {% for error in field.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex justify-content-center mt-4">
                            <input type="submit" value="Conferma" class="btn btn-primary btn-block" style="font-weight: bold;">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Modena_Eventi/utenti/templates/utenti/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Registrazione Utente{% endblock %}

{% block content %}
<style>
    .card-header {
        background-color: #e0e0d1; /* Beige */
        color: #333; /* Colore scuro per il testo */
        font-weight: bold;
    }
    
    .card {
        border-radius: 12px; /* Arrotonda gli angoli della card */
    }
    .btn-block {
        border-radius: 25px;
        padding: 10px 20px;
        font-size: 1.1rem;
    }
    .row.py-2 {
        margin-bottom: 1rem;
    }
    .container {
        max-width: 500px;
    }
    h2 {
        font-size: 2rem;
        margin-bottom: 1.5rem;
    }
</style>

<section class="mx-auto py-5 text-center">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2 class="text-dark">Registrazione</h2>
            </div>
            <div class="card-body">
                <div class="row py-2">
                    <a class="btn btn-lg btn-primary btn-block" href="{% url 'utenti:utente_registration' %}">Sono un utente</a>
                </div>
                <div class="row py-2">
                    <a class="btn btn-lg btn-primary btn-block" href="{% url 'utenti:pubblicatore_registration' %}">Sono un pubblicatore</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}